### ISSUE TITLE
Asciimath matrix not rendered correctly

### ISSUE THREAD

**Issue by peter-jerry-ye** [asciidoctor/asciidoctor-mathematical#108]
## Problem
The asciimath matrix is not rendered correctly

### Input
```asciidoc
= Test
:stem: 

== Content
stem:[[[1,2,3\], [4,5,6\]\]]
```

### Command
` asciidoctor-pdf -r asciidoctor-mathematical Test.adoc`

### Expected
![image](https://user-images.githubusercontent.com/16731997/137296862-c1b9ed5c-7aeb-4b66-a665-eca3e920a6b4.png)

### Output
![image](https://user-images.githubusercontent.com/16731997/137296916-6ef4fdc7-dca3-4867-aff3-c640bf2baeb5.png)

## Gem Versions

Ascii85 (1.1.0)
asciidoctor (2.0.16)
asciidoctor-mathematical (0.3.5)
asciidoctor-pdf (1.6.1)
asciimath (2.0.3)

**Comment by ProgramFan** [comment]
Have your tried to use asciimath macro directly? To my best knowledge, the above case shall not work since it does not specify the stem type. We encourage to use the concrete stem macro directly.

**Comment by peter-jerry-ye** [comment]
> Have your tried to use asciimath macro directly? 

You mean like this:
```asciidoc
= Test
:stem:

== Content
asciimath:[[[1,2,3\],[4,5,6\]\]]
```
It doesn't work either, nor with this one
```asciidoc
= Test
:stem:

== Content
[asciimath]
++++
[[1,2,3\],[4,5,6\]\]
++++
```

> To my best knowledge, the above case shall not work since it does not specify the stem type. We encourage to use the concrete stem macro directly.

This is the exact example given in the [official document of asciidoc](https://docs.asciidoctor.org/asciidoc/latest/stem/), so I don't see why it shall not work.

**Comment by ProgramFan** [comment]
There used to be an asciimath handler, it seems the the handler does not work.

**Comment by ProgramFan** [comment]
How about `[[1,2,3],[4,5,6]]` in block stem? The handler is still there in the code and shall work.

**Comment by peter-jerry-ye** [comment]
> How about `[[1,2,3],[4,5,6]]` in block stem?

It renders correctly.

**Comment by ProgramFan** [comment]
OK. This seems a problem in the expression itself. You do not have to escape them in block macros. The inline macro can not handle `[]` at the moment, unfortunately.

**Comment by Fethbita** [comment]
Is it possible to open this issue back? The `[]` still does not work for the inline macro, and this is the example given in the [documentation](https://docs.asciidoctor.org/asciidoc/latest/stem/#inline).
```adoc
A matrix can be written as stem:[[[a,b\],[c,d\]\]((n),(k))].
```
should be:
![image](https://github.com/user-attachments/assets/39282dfe-3543-48ec-85a8-3afcc9d00ab6)

but results in:
![image](https://github.com/user-attachments/assets/1f6a984d-cb4c-4024-8c51-42ff5ed9e274)

And even inside a block stem, the example does not work:
```adoc
A matrix can be written as 
[stem]
++++
[[[a,b],[c,d]]((n),(k))]
++++
```
results in:
![image](https://github.com/user-attachments/assets/d3220f60-af75-467f-836a-42bea02b767c)

which is not how it looks in the documentation.

**Comment by Fethbita** [comment]
@mojavelinux

**Comment by mojavelinux** [comment]
@Fethbita Please do not ping me on issues. If you have questions, you are free to ask them in the project chat at https://chat.asciidoctor.org.

**Comment by Fethbita** [comment]
Hey sorry for that. I can't re-open this issue myself, that's why I pinged you instead of creating a new issue and duplicating it.

**Comment by mojavelinux** [comment]
The issue is closed and should not be reopened. If a new issue is happening, then it should be reported as a new issue.
