### ISSUE TITLE
How should i escape the symbol name

### ISSUE THREAD

**Issue by eastack** [asciidoctor/asciidoctor-mathematical#111]
## Input
````
stem:[TMin_W]
````

## Expected
![image](https://user-images.githubusercontent.com/17524858/154616840-3bc84d5f-ded6-43a2-b017-3fe8cab90a45.png)

## Output

![image](https://user-images.githubusercontent.com/17524858/154617021-26c2cee0-e953-4ec0-b6a4-869564231392.png)

**Comment by AnnPin** [comment]
According to the documentation of [AsciiMath](http://asciimath.org), `stem:["TMin"_W]` seems to be the proper way to do it.
