### ISSUE TITLE
Invitation to join the Asciidoctor organization

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-mathematical#12]
On behalf of the Asciidoctor project, I'd like to invite this extension into the Asciidoctor organization on GitHub. Reply to this thread if you are interested and I'll get you set up with the permissions to transfer the repository and I will make you the owner of the repository. GitHub will automatically redirect visitors to the new URL.

I also encourage you to add Asciidoctor Mathematical to the list of official extensions on asciidoctor.org. See http://asciidoctor.org/docs/extensions/#official-extensions.

**Comment by ProgramFan** [comment]
I am interested in this extension joining the Asciidoctor organization and I am willing to maintain it. How about you, @tstumm?

**Comment by ProgramFan** [comment]
Given the moderate complexity, I think I have some time for maintaince, at least enough time to make it usable (adding new features is another thing, but for a simple extension like this, there shall not be too much new features to add). @tstumm @mojavelinux

**Comment by mojavelinux** [comment]
Excellent!

You don't have to stress too much about actively maintaining the repository. Part of bringing it into the Asciidoctor organization is to get help from the broader community. That's been true of every module so far. And I can tell you that there are many who have a vested interest in improving STEM support, so this one should certainly attract a few committed contributors.

I have sent you both an invite to join the Asciidoctor organization and opened up access to transfer the repository to Asciidoctor. Once you have joined, you can transfer the repository by following these steps.

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization

Once the transfer is complete, I will configure you both as administrators and team maintainers.

@tstumm will probably need to do the transfer, though it depends on what leave of access @ProgramFan has.

Welcome!

**Comment by tstumm** [comment]
Just finished transferring the repo :)

**Comment by mojavelinux** [comment]
Great! I'll complete the setup!

**Comment by mojavelinux** [comment]
Setup complete! Let me know if you have any troubles.
