### ISSUE TITLE
width and height values should be unitless

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-mathematical#14]
At least when outputting to HTML, the width and height values should be unitless. HTML forbids units on the value of the width and height attributes of the `<img>` tag.

I can understand for PDF output wanting to add units. However, even then, the units are assumed to be pixels (just as the input is) and the converter will deal with them appropriately. So I don't we should add units at all.

**Comment by ProgramFan** [comment]
I will investigate this once #11 is resolved.

**Comment by mojavelinux** [comment]
I also noticed that you dropped the height attribute. Even though the converters don't use the height, I still think you should pass that information through as it could be useful to another extension or the converter.

**Comment by ProgramFan** [comment]
OK. I will add them.
