### ISSUE TITLE
Publish version 0.1 and use semantic versioning

### ISSUE THREAD

**Issue by ProgramFan** [asciidoctor/asciidoctor-mathematical#22]
Since a lot of new stuff are added recently, I think it's time to publish a new version to rubygems so that broader users can benifit from it.

I would like to use semantic versioning and mark this version as 0.1.

**Comment by ProgramFan** [comment]
How about you? @tstumm @mojavelinux

**Comment by mojavelinux** [comment]
Let's use v0.1.0 instead. I think we should stick to the three number scheme.

**Comment by ProgramFan** [comment]
Thanks for correction. We will use v0.1.0

**Comment by tstumm** [comment]
We could use PI as versioning format. Start with 3 and add the decimal places as we go... Just kidding, three number scheme is fine.

**Comment by ProgramFan** [comment]
I will then mark the latest trunk v0.1.0.

**Comment by ProgramFan** [comment]
I have marked the release. Would you push a new gem to rubygems? @tstumm. I can make the push if you don't mind.

**Comment by tstumm** [comment]
I just published 0.1.0 on rubygems. Sorry for the delay.

**Comment by mojavelinux** [comment]
Brilliant! Thanks @tstumm!

**Comment by ProgramFan** [comment]
Nice job. @tstumm
