### ISSUE TITLE
Specify additional packages

### ISSUE THREAD

**Issue by jonocarroll** [asciidoctor/asciidoctor-mathematical#25]
I'm using `asciidoctor-mathematical` behind `asciidoctor-pdf` and while I can now get equations to show up in passthrough blocks, I still need to have additional LaTeX packages loaded.

Is there a way to add, say, `\usepackage{mathtools}` to something like the preamble?

**Comment by ProgramFan** [comment]
Probably not.

asciidoctor-mathematical uses *mathematical* to convert latex-style math equations to images. mathematical uses its own latex grammar parser and no macros except these used widely in math equations are allowed. Loading latex packages is not an option, and it is unlikely to be.

If you really need extra packages to support your maths in asciidoctor, I would suggest use asciidoctor-latex to convert the document directly into latex document, so anything can be possible.

**Comment by jonocarroll** [comment]
Fair enough. Thanks for the quick reply.
