### ISSUE TITLE
Fail instalation on Windows

### ISSUE THREAD

**Issue by lit-uriy** [asciidoctor/asciidoctor-mathematical#29]
`gem install asciidoctor-mathematical`
generates a huge number of errors, for some reason dependencies are not installed automatically.
Did anybody install this on Windows

**Comment by tstumm** [comment]
Please post your log.

**Comment by lit-uriy** [comment]
'''
current directory: c:/Programs/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mathematical-1.6.9/ext/mathematical
c:/Programs/Ruby200-x64/bin/ruby.exe -r ./siteconf20170519-6012-nc2zz.rb extconf.rb
checking for cmake... yes
checking for main() in -lxml2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=c:/Programs/Ruby200-x64/bin/ruby
	--with-xml2lib
	--without-xml2lib
c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:714:in `try_func'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:944:in `block in have_library'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:889:in `block in checking_for'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:888:in `checking_for'
	from c:/Programs/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:939:in `have_library'
	from extconf.rb:45:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  c:/Programs/Ruby200-x64/lib/ruby/gems/2.0.0/extensions/x64-mingw32/2.0.0/mathematical-1.6.9/mkmf.log

extconf failed, exit code 1
'''

**Comment by tstumm** [comment]
Please try to install the Ruby DevKit. 

https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

**Comment by lit-uriy** [comment]
Ruby DevKit installed, and i run **devkitvars.bat**, to update PATH variable.
I am instal **mathematical** gem manual, libxml-dev too. When I explicitly the manual installation of gems, no error occurs.
There are a large number of gems that need to install, I can't do it all by hand.

**Comment by crra** [comment]
@lit-uriy: check if you have installed: `mingw-w64-x86_64-gcc` via `pacman -S mingw-w64-x86_64-gcc`

**Comment by ProgramFan** [comment]
Duplicated as #36
