### ISSUE TITLE
Support for asciidoctor-latex

### ISSUE THREAD

**Issue by tribut** [asciidoctor/asciidoctor-mathematical#31]
Could this package be made to work with formulas generated with [asciidoctor-latex](https://github.com/asciidoctor/asciidoctor-latex)? I was hoping that something like this would work:

    asciidoctor -b html -r asciidoctor-mathematical -r asciidoctor-latex -a stem=latexmath file.adoc

But it only converts the stem expressions generated by `stem[x^2]`, not those by asciidoctor-latex syntax (`$x^2$`). Would be great if interoperability could be achieved.

**Comment by ProgramFan** [comment]
asciidoctor-bibtex does provide public APIs for this task. One has to hack into asciidoctor-latex source to extract APIs to hook its formula handling. Any PR is welcoming. 😄
