### ISSUE TITLE
asciidoctor-mathematical-0.2.2 will not recognize mathematical-1.6.9 

### ISSUE THREAD

**Issue by oM3fC** [asciidoctor/asciidoctor-mathematical#32]
This may well be my own misunderstanding so I'm happy for any help to correct it. What further information can I provide?

with Kali 2017.1 fully updated and required dependencies and gems installed:

cat /etc/debian_version 
kali-rolling

Successfully installed prawn-2.1.0
1 gem installed
Successfully installed prawn-templates-0.0.3
1 gem installed
Building native extensions.  This could take a while...
Successfully installed mathematical-1.6.9
1 gem installed
Successfully installed asciidoctor-pdf-1.5.0.alpha.16
1 gem installed
Successfully installed asciidoctor-mathematical-0.2.2
1 gem installed

ls -lha /var/lib/gems/2.3.0/gems/mathematical-1.6.9/lib/mathematical/

total 388K
drwxr-xr-x 2 root root 4.0K Sep 16 14:59 .
drwxr-xr-x 3 root root 4.0K Sep 16 14:58 ..
-rw-r--r-- 1 root root  404 Sep 16 14:58 configuration.rb
-rw-r--r-- 1 root root  482 Sep 16 14:58 corrections.rb
-rwxr-xr-x 1 root root 364K Sep 16 14:59 mathematical.so
-rw-r--r-- 1 root root 1.4K Sep 16 14:58 validator.rb
-rw-r--r-- 1 root root   50 Sep 16 14:58 version.rb

asciidoctor-pdf -v --require asciidoctor-mathematical --doctype book ./test.adoc

liblasem.so: cannot open shared object file: No such file or directory - /var/lib/gems/2.3.0/gems/mathematical-1.6.9/lib/mathematical/mathematical.so
  Use --trace for backtrace

shell returned 1

/var/lib/gems/2.3.0/gems/mathematical-1.6.9/lib/mathematical/mathematical.so exists but asdciidoctor-mathematical does not see it?

Is there a missing environmental variable or some such? I can't see an issue with permissions given that user is Root.

**Comment by oM3fC** [comment]
Confirmed all dependencies appear to be installed also

aptitude search bison flex libffi-dev libxml2-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev ttf-lyx | grep -i -e "i "

i  bison - YACC-compatible parser generator
i A flex - fast lexical analyzer generator
i A libbison-dev - YACC-compatible parser generator - development library
i  libcairo2-dev - Development files for the Cairo 2D graphics library
i A libffi-dev - Foreign Function Interface library (development files)
i  libgdk-pixbuf2.0-dev - GDK Pixbuf library (development files)
i  libpango1.0-dev - Development files for the Pango
i  libxml2-dev - Development files for the GNOME XML library
p  pd-flext-doc - Flext C++ external layer for Pd (API documentation)
i  ttf-lyx - transitional package

**Comment by ProgramFan** [comment]
It seems the same problem as #30, which is a bug in mathematical. See workarounds there.
