### ISSUE TITLE
Windows Installation - Enhancemenet

### ISSUE THREAD

**Issue by slaanco** [asciidoctor/asciidoctor-mathematical#35]
Hi,

it would be awesome, if you could provide instructions about how to install asciidoctor-mathematical on Windows. Are there any plans for this?

Thank you!

**Comment by ProgramFan** [comment]
asciidoctor-methematical is ruby-only. So it can possibly run out of the box on Windows. But mathematical, on which asciidoctor-mathematical depends, is a native extension and is not known to support Windows at the moment.
