### ISSUE TITLE
Cannot install asciidoctor-mathematical (Windows)

### ISSUE THREAD

**Issue by msander1983** [asciidoctor/asciidoctor-mathematical#36]
I'm having trouble installing asciidoctor-mathematical on my Windows machine.

This is the log from running >gem install asciidoctor-mathematical: 

> current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mathematical-1.6.11/ext/mathematical
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180130-292-1o024en.rb extconf.rb
checking for cmake... yes
checking for -lxml2... no
checking for -lpangocairo-1.0... no
checking for libxml/tree.h in /include/libxml2,/usr/include/libxml2,/usr/local/include/libxml2... no
checking for libxml/parser.h in /include/libxml2,/usr/include/libxml2,/usr/local/include/libxml2... no
checking for libxml/xpath.h in /include/libxml2,/usr/include/libxml2,/usr/local/include/libxml2... no
checking for libxml/xpathInternals.h in /include/libxml2,/usr/include/libxml2,/usr/local/include/libxml2... no
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.16299.
-- The C compiler identification is MSVC 19.10.25017.0
-- The CXX compiler identification is MSVC 19.10.25017.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find BISON (missing: BISON_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBISON.cmake:252 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:61 (find_package)

> -- Configuring incomplete, errors occurred!
See also "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mathematical-1.6.11/ext/mathematical/mtex2MML/build/CMakeFiles/CMakeOutput.log".
make: *** Ingen regel för att skapa målet ”libmtex2MML_static”.  Stannar.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

> Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/Ruby24-x64/bin/$(RUBY_BASE_NAME)
	--with-xml2lib
	--without-xml2lib
	--with-pangocairo-1.0lib
	--without-pangocairo-1.0lib
	--use-system-mtex2MML
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1225:in `stat': No such file or directory @ rb_file_s_stat - C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mathematical-1.6.11/ext/mathematical/mtex2MML/build/libmtex2MML.a (Errno::ENOENT)
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1225:in `lstat'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1254:in `copy'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:416:in `block in copy_entry'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1388:in `wrap_traverse'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:413:in `copy_entry'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:391:in `block in cp_r'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1461:in `block in fu_each_src_dest'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1475:in `fu_each_src_dest0'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1459:in `fu_each_src_dest'
	from C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:390:in `cp_r'
	from extconf.rb:79:in `<main>'

> To see why this extension failed to compile, please check the mkmf.log which can be found here:

>   C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/mathematical-1.6.11/mkmf.log

> extconf failed, exit code 1

**Comment by ProgramFan** [comment]
The problem is that mathematical does not yet compile on windows. This is what the messages say. I am not confident enough in whether it will eventually work on that platform.
