### ISSUE TITLE
Output mostly broken with asciidoctor-pdf, less broken with asciidoctor to HTML

### ISSUE THREAD

**Issue by krjackson** [asciidoctor/asciidoctor-mathematical#41]
Rendering sample.adoc to PDF with `asciidoctor-pdf` does not convert most of the math at all, and the `\sqrt` symbol is broken. When rendering to HTML with `asciidoctor`, most of the math in the sample doc renders correctly, except the `\sqrt`, which is still an S with a line.

I'm running Ruby 2.5.1 via RVM on OpenSUSE Tumbleweed. 

[test.pdf](https://github.com/asciidoctor/asciidoctor-mathematical/files/2462516/test.pdf)
Screenshot of HTML:
![html](https://user-images.githubusercontent.com/12878689/46703915-64e22f80-cbee-11e8-992e-e238d2344f28.png)

**Comment by ProgramFan** [comment]
There might be something wrong. If you can find the formula images under images directory in the same directory as the HTML file, asciidoctor-mathematical shall work.

**Comment by Tommassino** [comment]
Hey, ran into issues with the renderer aswell:

`stem:[0 \in \{0, 1, 2, 3\}]` gets rendered as
![stem-2d450f409d1d8078235bc2ca31ea4e6f](https://user-images.githubusercontent.com/698950/46938353-d7766380-d063-11e8-8228-7fe4cc4bb824.png)

I do not have the same issue with sqrt as the OP has though.

stem:[\sqrt 4 = 2] gets rendered correctly

**Comment by krjackson** [comment]
Most of my problem was the fonts. As I usually also have a full TeX install, the fonts expected by the mathematical gem are already present. In this case they weren't. That doesn't address the issue with the equations in cells when using asciidoctor-pdf, though. As that's not an immediate issue for me, I'll close this issue.
