### ISSUE TITLE
Some math symbols get incorrectly rendered

### ISSUE THREAD

**Issue by Tommassino** [asciidoctor/asciidoctor-mathematical#42]
Hey, ran into issues with the renderer aswell. It looks that the default font in asciidoctor-pdf does not support a lot of the unicode math symbols.

stem:[0 \in \{0, 1, 2, 3\}] gets rendered as
![stem-2d450f409d1d8078235bc2ca31ea4e6f](https://user-images.githubusercontent.com/698950/46940652-823d5080-d069-11e8-9287-0234dc9aad00.png)
Image taken directly from images/stem-*

I do not have the same issue with sqrt as the OP has though.

stem:[\sqrt 4 = 2] gets rendered correctly

Details on how to reproduce:
Dockerfile of my asciidoctor image
```
FROM asciidoctor/docker-asciidoctor

RUN gem install asciidoctor-mathematical --no-ri --no-rdoc

CMD ["/bin/bash"]
```
command that I use to build:
`docker run --rm -v ${PWD}:/documents/ asciidoctor_withmath asciidoctor-pdf -r asciidoctor-mathematical test.adoc`

Related issues: 
https://github.com/asciidoctor/docker-asciidoctor/issues/78
https://github.com/asciidoctor/asciidoctor-mathematical/issues/41

**Comment by Tommassino** [comment]
Workaround - add these fonts to render symbols:
```
apk add ttf-dejavu
```

**Comment by ProgramFan** [comment]
So it shall be caused by missing fonts. The workaround is the solution.

**Comment by dduportal** [comment]
For later readers: the font `ttf-dejavu` is now installed by default in the image.
