### ISSUE TITLE
publish version 0.3.0

### ISSUE THREAD

**Issue by hakandilek** [asciidoctor/asciidoctor-mathematical#49]
@tstumm do you mind publishing the new version to rubygems?

asciidoctor/docker-asciidoctor#89 needs this version to continue.

**Comment by ProgramFan** [comment]
I am happy for the release. But @tstumm is the owner on rubygems.

**Comment by ProgramFan** [comment]
Let's wait a couple of days for @tstumm. Shall he be not available, I can make the release for him.

**Comment by tstumm** [comment]
Done, sorry for the delay.
