### ISSUE TITLE
Wrong display of brackets in PDF output

### ISSUE THREAD

**Issue by JanFeld** [asciidoctor/asciidoctor-mathematical#53]
Hi,

i'm experiencing some issues when creating PDFs using asciidoctor-pdf and asciidoctor-mathematical.

Brackets are not displayed correctly. They are replaced with other symbols.

**Source:**
```
[latexmath]
++++
\dfrac{\text{Vermögen}(GK = AV + UV)}{\text{Schulden} (FK)} = \text{Reinvermögen} (EK)
++++
```

**Issue:**
![asciidoctor-mathematical-issue](https://user-images.githubusercontent.com/22739965/56790902-12710500-6806-11e9-9bb0-f37cc051d916.png)

**System:**
* Arch Linux - 5.0.9
* asciidoctor-pdf 1.5.0.alpha.17
* asciidoctor 2.0.8
* asciidoctor-mathematical (0.3.0, 0.2.2)

Thanks in advance!

Best regards,
Jan

**Comment by xrayn** [comment]
In case s.b. has similar issues, this fixed it for me: `pacman -S ttf-computer-modern-fonts`

**Comment by ProgramFan** [comment]
This is indeed a font problem.

**Comment by vadz** [comment]
In case it can help somebody else, under Debian these fonts can be found in `fonts-lyx` package.
