### ISSUE TITLE
Can't add tag to equations

### ISSUE THREAD

**Issue by Nathan-Furnal** [asciidoctor/asciidoctor-mathematical#57]
Hi, I'm having an issue with adding tags to equations :

So I'm adding, 
`:stem: latexmath`

then, 

```
[stem]
++++
\begin{align*}

\dot{x} = \dfrac{dx}{dt} \\

\dot{y} = \dfrac{dy}{dt} \tag{1.a}

\end{align*}
++++
```

This works in mathjax but does not when I use asciidoctor-mathematical. How can I fix it ?

Thanks

**Comment by ProgramFan** [comment]
I suspect that the `\tag` command is not a valid latex macro.

**Comment by Nathan-Furnal** [comment]
@ProgramFan 

It is part of amsmath but it should be working

**Comment by ProgramFan** [comment]
That is the problem. asciidoctor-mathemmatical uses mathematical, which in turn uses mtex2mml for latex support, and mtex2mml does not recognize the `\tag` macro and simply drops it. See https://github.com/gjtorikian/mtex2MML/blob/master/SUPPORTED.md#t for more details.

**Comment by ProgramFan** [comment]
I will close this issue since it shall be reported upstream.
