### ISSUE TITLE
:mathdir: attribute like :imagedir: for asciidoctor-mathematical (Feature Request)

### ISSUE THREAD

**Issue by oyren** [asciidoctor/asciidoctor-mathematical#62]
Would it be possible to add something like `:imagedir:` to separate the SVG and PNG generated by asciidoctor-mathematical from the user/normal images? For example a `:mathdir:` attribute.

**Comment by lurch** [comment]
Isn't that what `:imagesoutdir:` is for?

**Comment by oyren** [comment]
> Isn't that what `:imagesoutdir:` is for?

Thanks for the tip that works.
