### ISSUE TITLE
Math expressions syntax

### ISSUE THREAD

**Issue by WyRe** [asciidoctor/asciidoctor-mathematical#64]
I was wondering why the extension does not support the typical syntax for math expressions, I mean, when you use 

```
:stem: latexmath

= Title

whatever expression you want \(\quad \rightarrow \quad a^2 + b_c = \sqrt{h\cdot d}\)
```

It is not being rendered, it is necessary to use always `latexmath:[]` or `stem:[]` to get them rendered? I find this pretty bothering. I'd prefer a more latex-like behaviour.

**Comment by ProgramFan** [comment]
The `\( \)` are not part of the asciidoc syntax, so they do not go through this extension. asciidoctor-latex can handle it.

**Comment by WyRe** [comment]
@ProgramFan `asciidoctor-latex` is not as functional as I would like with tables and lists, see https://github.com/asciidoctor/asciidoctor-latex/issues/85 so ... what do you recommend me to produce a readable pdf when I'm using `\(\)` latex syntax inside tables or lists?

**Comment by ProgramFan** [comment]
Maybe one can write a preprocessor to convert this to stem:[]. But before this happens, there seems no direct support for the `\(\)` syntax. Would you mind using a regex replace to change them into the standard asciidoc stem syntax?

**Comment by WyRe** [comment]
@ProgramFan that's a good suggestion, but the point is in LaTex the `\(\)` is not the same than `\[\]` (which I'm also using in my docu despite it does not appear in initial MWE).

The second one is used to force a displayed math environment, so you'll get the equation in a new line. 

The first one is used to inline math mode. As you can see [here](https://latex.org/forum/viewtopic.php?p=77570&sid=d278b791d9ee4effdec803aeb8b7b816#p77570) 

I guess there is not such a difference like this in `asciidoc` unfortunately.

**Comment by ProgramFan** [comment]
Regex would be a much simpler tool. In most cases, `cat <FILE> | sed -e 's/\(/stem:[/g' | sed -e 's/\)/]` will  do the first and a similar one will do the second.

**Comment by WyRe** [comment]
Oh, yes, but I was talking about differences between inline math mode and display math mode in `asciidoc` there exist those different modes? Or maybe are just all `stem:[]`?

**Comment by ProgramFan** [comment]
Yes. The following is for display mode:

```asciidoc
[stem]
++++
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
++++
```

**Comment by WyRe** [comment]
And could be that used inside nested lists?

**Comment by ProgramFan** [comment]
Insert a plus sign after the "Inside a":
```asciidoc
* What about a stem block
** Inside a
+
[stem]
++++
a^2+b^2=c^2
++++
nested list?
```

You should do this in the original asciidoc file, too. It's asciidoc's rule to force continuation of a multiline list item.

**Comment by WyRe** [comment]
@ProgramFan Thank you for your help, this one-liner did the work

```
cat <file> | sed -e 's/\\(/stem:[/g' | sed -e 's/\\)/]/g' | sed -e 's/\\\[/\n+\n[stem]\n++++\n/g' | sed -e 's/\\]/\n++++\n/g' | sed 's/^[ \t]*//' > <file_converted>
```

However ... there is still a situation where I don't get properly results, when I have something like 

```
\(\frac{[E]}{d}\)
```

The conversion will be 

```
stem:[\frac{[E]}{d}]
```

Which is interpreted like `stem:[\frac{[E]` so ... how could I use `[]` inside `stem:[]` ? is there a kind of escape character?

**Comment by ProgramFan** [comment]
IMO, `stem:[\frac{[E]}{d}]` should work since using brackets is very common in math typesetting.

**Comment by WyRe** [comment]
> IMO, `stem:[\frac{[E]}{d}]` should work since using brackets is very common in math typesetting.

I thought exactly that, square brackets are so common in math syntax and this should be rendered usually, but did not work in my case and you have not any similar example [in here](https://github.com/asciidoctor/asciidoctor-mathematical/blob/master/sample.adoc) with those squared brackets, I mean. 

Could you try and confirm me? Also I've detected a few render issues that I'm going to report in #67
