### ISSUE TITLE
asciidoctor: WARNING: conversion missing in backend pdf for stem

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-mathematical#66]
Get this error when using 0.3.1 of asciidoctor-mathematical and running asciidoc from docker image (https://github.com/asciidoctor/docker-asciidoctor/blob/master/Dockerfile):
```
bash-5.0# asciidoctor-pdf --trace -d book -r asciidoctor-diagram -r asciidoctor-mathematical chap02.adoc
asciidoctor: WARNING: conversion missing in backend pdf for stem
asciidoctor: WARNING: conversion missing in backend pdf for stem
asciidoctor: WARNING: conversion missing in backend pdf for stem
```

The math content does not render in the pdf. Here is example math content:
```
[stem]
++++
sig = enc(H(D), s)
++++
```

**Comment by mojavelinux** [comment]
Asciidoctor PDF no longer issues this warning. If the extension is unavailable or cannot be loaded, the equation is emitted in a code block.

**Comment by mojavelinux** [comment]
If you upgrade to asciidoctor-mathematical 0.3.4, the generic stem block is now supported. Though note that you may want to wait for 0.3.5, as there are some other pending issues you'll hit with 0.3.4.

**Comment by lucki1000** [comment]
Hi,
I've installed 10mins ago asciidoctor-mathematical over gem with this syntax: 
```
sudo gem install asciidoctor-mathematical 
Successfully installed asciidoctor-mathematical-0.3.5
Parsing documentation for asciidoctor-mathematical-0.3.5
Done installing documentation for asciidoctor-mathematical after 0 seconds
1 gem installed
```  
then i ran:
```
asciidoctor-pdf -r asciidoctor-kroki -r asciidoctor-mathematical lf04/index.adoc
```
and get this:
``` 
asciidoctor: WARNING: conversion missing in backend pdf for stem
```
