### ISSUE TITLE
Brackets inside stem macro and block are not properly rendered.

### ISSUE THREAD

**Issue by WyRe** [asciidoctor/asciidoctor-mathematical#67]
Well, here the MWE

```asciidoc
:stem: latexmath

== This is a test

[stem]
++++
NH_4NO_2(s)
++++

. Now inside a list item stem:[NH_4NO_2(s)]
```

This is the result I'm getting after conversion with 

```bash
asciidoctor-pdf -r asciidoctor-mathematical -o test.pdf test.adoc
```

![Captura de pantalla_2019-12-20_14-32-31](https://user-images.githubusercontent.com/4059108/71258066-98156800-2335-11ea-9d43-43ac9341f6ed.png)

**Comment by ProgramFan** [comment]
Would you please check if it works under asciidoctor alone in the html renderer? It seems that you are lacking some fonts.

**Comment by WyRe** [comment]
For `.html` format is all working as expected.

**Comment by WyRe** [comment]
@ProgramFan I've also detected problems in single letters rendering, it is rendering them as a superscripts as you can see in the screenshot. Otherwise  the `test.html` file is properly rendered when I get it from `asciidoctor test.adoc`

![Captura de pantalla_2019-12-20_16-59-22](https://user-images.githubusercontent.com/4059108/71267202-5216cf00-234a-11ea-84f6-cb59d8e0f9f8.png)

**Comment by ProgramFan** [comment]
I can confirm the rendering of brackets is an issue of missing fonts. Install all fonts as stated in mathematical page https://github.com/gjtorikian/mathematical. This is what I get on macOS:

<img width="786" alt="图片" src="https://user-images.githubusercontent.com/32396/71302470-3103bc00-23e6-11ea-8fd7-82dbf650c508.png">

The `i` and `n` problem is caused by the font size, which, however, does not have any solutions yet.

**Comment by WyRe** [comment]
@ProgramFan well, you were right about fonts, I've solved the issue installing [this package](https://aur.archlinux.org/packages/ttf-computer-modern-fonts/) in Arch; however 

- I'd consider that as a valuable info which could be added to the [readme](https://github.com/asciidoctor/asciidoctor-mathematical#dependencies) in the Arch Linux case. 

- Also I cannot understand you won't consider the problem for single letter for in-line math mode as a valid issue.

- Is not there an argument to prevent those multiple `stem-<code>.png` pictures be generated? At least to clean after runtime?

**Comment by ProgramFan** [comment]
The issue is considered invalid because asciidoctor-mathematical can do nothing since it is caused by mathematical itself. Whether mathematical will consider it an issue depends on mathematical itself.

For the stem-xxxxx.png, unfortunately, asciidoctor-mathematical can not delete them on its own. asciidoctor-mathematical is meant to be used as a plugin, so you can use it with the pdf, html, docbook and even epub3 backend. Only the pdf backend can safely remove the files after pdf generation. If you care about this, use a makefile do build pdf and clean the stem pngs at the same time.

For the first suggestion, an PR is welcome.

**Comment by WyRe** [comment]
@ProgramFan Are devs aware about this font issue in the mathematical repo? (I guess they are.)

**Comment by ProgramFan** [comment]
They are and they have instructions in the repo README. But they only have instructions for osx.

**Comment by WyRe** [comment]
Excuse me, could you specify where exactly those instructions are? I was reading the [readme](https://github.com/gjtorikian/mathematical/blob/master/README.md) and I could not find them.

**Comment by ProgramFan** [comment]
```
cd ~/Library/Fonts
curl -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/cmex10.ttf \
     -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/cmmi10.ttf \
     -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/cmr10.ttf \
     -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/cmsy10.ttf \
     -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/esint10.ttf \
     -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/eufm10.ttf \
     -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/msam10.ttf \
     -LO http://mirrors.ctan.org/fonts/cm/ps-type1/bakoma/ttf/msbm10.ttf
```

**Comment by WyRe** [comment]
But that's for install the fonts, what has that to do with font size, which is causing the issue for single letters size? 

Are those maybe fixed ones? Because in that case I could create a new AUR package to ship them to the system. As I've pointed in #68 those fonts are packaged in [this one](https://aur.archlinux.org/packages/ttf-computer-modern-fonts/) but even those are causing the smaller size than normal.

The package I mention fetches the fonts from http://distfiles.gentoo.org/distfiles/texcm-ttf.zip which is not exactly the same site than mathematical repo suggests, that's why I'm asking if there would be a difference and this size issue could be fixed shipping the suggested ones.

**Comment by ProgramFan** [comment]
Sorry to have misunderstood the issue. Based on my own experience, I have no idea how to deal with the font size problem. Mathematical converts the latex equation to MML and uses Lasem to convert MML to png and SVG. After the conversion, all font information is lost and only path information is recorded. So it can only be typeset as a fix-sized inline image and unfortunately, the produced image is just too small.

I would suggest you not to rely on this package for publication, but for drafting. For publication, asciidoctor + asciidoctor-latex + asciidoctor-bibtex is more friendly to play with.

**Comment by WyRe** [comment]
Well, @ProgramFan I appreciate your help and suggestions, but the point with `asciidoctor-latex` is that's not working as expected either, as you can see [in here](https://github.com/asciidoctor/asciidoctor-latex/issues/85) is not treating properly in-line expressions or math expressions inside items list or tables.
