### ISSUE TITLE
How to cross reference equations?

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-mathematical#69]
I am using asciidoc-mathematical with latex backend. I would like to know how to number equations and then cross-reference them in my doc. It seems the issue was reported in https://github.com/asciidoctor/asciidoctor-mathematical/issues/37 but I don't see any resolution.

I would like to see an example how to do above. If not possible, could this be prioritized please?

**Comment by ProgramFan** [comment]
Closed in favor of #37.
