### ISSUE TITLE
Difficulties vertically aligning inline latexmath

### ISSUE THREAD

**Issue by davidplowman** [asciidoctor/asciidoctor-mathematical#71]
Hi, apologies if this isn't the appropriate forum to seek advice, I'm afraid I've failed to find anything on the net.

I have a very simple example file, consisting of a single line (:

An inline equation latexmath:[w] and bigger latexmath:[{\large w}]. With subscripts latexmath:[w_{ij}] bigger latexmath:[{\large w_{ij}}]. (As plain text, not an equation, we get _w~ij~_)

and turn it into a pdf using

asciidoctor-pdf -r asciidoctor-mathematical -o test.pdf test.adoc

My problem is that the inline equations (whether using png or svg mode) don't sit on the line with the other text - and it gets worse when there are subscripts. Does anyone know of any techniques to work around this situation?

Thanks

**Comment by ProgramFan** [comment]
A screen shot for this?

**Comment by davidplowman** [comment]
Sorry, didn't know I could do that!

![screenshot](https://user-images.githubusercontent.com/38045873/71993881-bdf4a500-322f-11ea-9756-59d7a8897947.jpg)

**Comment by ProgramFan** [comment]
This problem needs help from asciidoctor-pdf. It is a problem of layout inline images. Would you please report there?

**Comment by davidplowman** [comment]
I've raised the issue here: https://github.com/asciidoctor/asciidoctor-pdf/issues/1483
so I'll close this one. Thanks for your help!
