### ISSUE TITLE
How to change font in stem equations

### ISSUE THREAD

**Issue by angelog0** [asciidoctor/asciidoctor-mathematical#80]
I wrote a document that uses `stem` equations and that I compile both with `ascidoctor` (to produce an HTML file) and `asciidoctor-pdf` (to produce a PDF file). With `asciidoctor-pdf` I use the extension `asciidoctor-mathematical` and `mathematical-format=svg`. 

Now in PDF output the font used for the equations is very poor. I am following [this](https://asciidoctor.org/docs/asciidoctor-pdf) document. There is a [section](https://asciidoctor.org/docs/asciidoctor-pdf/#fonts-in-svg-images) about the font in SVG images but I  do not understand how to change the font for `stem` equations: it reports the example for font in diagram not in `stem` equations. 

In the following archive there are two example, one from an HTM file and one from a PDF file, to proof tha bad quality font in PDF.

[font_demo.tar.gz](https://github.com/asciidoctor/asciidoctor-pdf/files/4564786/font_demo.tar.gz)

I would be grateful if you can suggest also a good font for that.

TIA,
  Angelo.

**Comment by ProgramFan** [comment]
Unfortunately, there exists no way to change the fonts. The fonts are converted into paths in the generated svgs and the only way to change fonts is to handle them in the library behind mathematical.

**Comment by bwklein** [comment]
Can we add a scaling factor?  My equations seem very 'squished' vertically.

**Comment by marioortizmanero** [comment]
This seems like a duplicate of #45 and could be closed. There's some interesting info in that issue but it's a bit stale.
