### ISSUE TITLE
Incorrect handling of inline AsciiMath

### ISSUE THREAD

**Issue by GarkGarcia** [asciidoctor/asciidoctor-mathematical#84]
This a follow up to https://github.com/asciidoctor/asciidoctor-mathematical/pull/82#issuecomment-632622291. I recently implemented AsciiMath support. It has just been released.

However, I now realize the `asciimath` inline macro is incorrectly handled. Basically, it is handled in exact the same way the `latexmath` inline macro is. That means the macro is not processing AsciiMath code, it's actually processing LaTeX directly. In other words, currently the `asciimath` inline macro is functionally equivalent to the `latexmath` inline macro. This is an error.

I'm working on a patch, but I may need some help on it. This issue was cause by my inability to comprehend how inline stem blocks are currently handled. I think I've now got things figured out, but I'd like someone to review the patch in detail to make sure the implementation is not broken again.

**Comment by GarkGarcia** [comment]
It is also worth noting that the `asciimath` block macro is working correctly.

**Comment by GarkGarcia** [comment]
This issue could be avoided in the future with the introduction of tests targeting the rendering of the `asciimath` inline and block macros.

**Comment by ProgramFan** [comment]
We need to refactor the code now. After a lot of edits, the code is messay.

**Comment by GarkGarcia** [comment]
Fixed on 050841e.
