### ISSUE TITLE
Does not convert inline stem content inside stem:[…]

### ISSUE THREAD

**Issue by jirutka** [asciidoctor/asciidoctor-mathematical#9]
Asciidoctor defines three stem macros: `stem`, `latexmath` and `asciimath`. The first one is generic; the actual format is specified by the `:stem:` attribute.

This extension handles it right for a block content, but not for an inline content. It works just with specific `latexmath` macro ([lib/asciidoctor-mathematical/extension.rb:87](https://github.com/tstumm/asciidoctor-mathematical/blob/91ba4dd438827c8c3e169823b49bc18a7c15881c/lib/asciidoctor-mathematical/extension.rb#L87)), `stem:[…]` is ignored.

**Comment by ProgramFan** [comment]
The `stem:[]` is ignored because this extension currently only handles latex style math correctly. Supporting asciimath is not impossible, but there are no plan yet. Maybe we can support `stem:[]` when we detect that it uses latexmath format.

**Comment by jirutka** [comment]
> Maybe we can support stem:[] when we detect that it uses latexmath format.

Yes, exactly. That’s how it already works for block macro, but not for inline macro. Please read my bug report more carefully. ;)

**Comment by mojavelinux** [comment]
In order to handle the inline stem macro, you need to register a custom inline macro for `stem` and also disable the `stem` document attribute in the Treeprocessor so the custom macro gets called. In other words, it requires a little bit of trickery atm.

**Comment by mojavelinux** [comment]
I misspoke about how to handling the inline stem macro. I corrected the recommended approach in #11.

> Maybe we can support stem:[] when we detect that it uses latexmath format.

Actually, what you want to do is look for `stem:[]` and then check to see if the `stem` attribute has the value `latexmath`.

```ruby
document.attr? 'stem', 'latexmath'
```

That effectively makes the `stem:[]` macro a `latexmath:[]` macro (it's a shorthand).

**Comment by mojavelinux** [comment]
This will be addressed by the fix for #11.

**Comment by ProgramFan** [comment]
#11 seems a nice approach. Please check back when it is addressed.

**Comment by ProgramFan** [comment]
This shall already be addressed by the latest revision.  Would you please verify it, @jirutka ?

**Comment by ProgramFan** [comment]
I verified the stem:[xx] works for inline equations, so this is closed.
